/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#c6decb",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed-variant": "#003ea8",
        "outline-variant": "#9bbca7",
        "primary-container": "#00873a",
        "on-primary-fixed-variant": "#005320",
        "tertiary": "#5d5c5b",
        "surface-container-highest": "#b1dabe",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002109",
        "surface-bright": "#e6f2eb",
        "secondary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#7ffc97",
        "on-tertiary-fixed-variant": "#474646",
        "surface-container": "#c9e6d4",
        "surface-container-low": "#d9ece0",
        "surface-tint": "#006e2d",
        "secondary-container": "#316bf3",
        "on-secondary-fixed": "#00174b",
        "on-surface": "#012613",
        "background": "#e6f2eb",
        "on-error": "#ffffff",
        "outline": "#4b6c55",
        "secondary-fixed": "#dbe1ff",
        "surface": "#e6f2eb",
        "on-tertiary": "#ffffff",
        "on-background": "#012613",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#f2f9f5",
        "on-tertiary-fixed": "#1c1b1b",
        "primary-fixed-dim": "#62df7d",
        "inverse-surface": "#1e3a2b",
        "inverse-on-surface": "#e6f2eb",
        "on-primary-container": "#f7fff2",
        "on-tertiary-container": "#f7feff",
        "secondary": "#0051d5",
        "primary": "#006b2c",
        "tertiary-container": "#767474",
        "tertiary-fixed": "#e5e2e1",
        "surface-variant": "#bcdbc6",
        "error-container": "#ffdad6",
        "inverse-primary": "#62df7d",
        "error": "#ba1a1a",
        "on-surface-variant": "#1c4a2f",
        "on-secondary-container": "#fefcff",
        "surface-container-high": "#bcebce"
      },
      fontFamily: {
        "headline": ["Antonio", "Space Grotesk", "sans-serif"],
        "body": ["Archivo Narrow", "Inter", "sans-serif"],
        "label": ["Archivo Narrow", "Inter", "sans-serif"],
        "antonio": ["Antonio", "sans-serif"],
        "archivo": ["Archivo Narrow", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
